image: python2.7
script:
  - docker/restore-mtime.sh

publish:
  docker:
    docker_host: $$DOCKER_HOST
    docker_version: 1.3.0
    registry_login: true
    registry_login_url: $$LOGIN_URL
    username: $$LOGIN_USER
    password: $$LOGIN_PASS
    email: $$LOGIN_EMAIL
    image_name: i.scrapinghub.com/portia/$CI_BRANCH

cache:
  - /home/ubuntu/.npm
  - /home/ubuntu/.cache
